### PR TITLE
Add auctex faces

### PR DESCRIPTION
**Pull request by justbur**
I love this theme but some of the auctex faces were set to the default. This just makes some minimal changes, including the sectioning commands and the math face.

### CODE REVIEW

**Comment by justbur** [comment]
Let me know if you want me to change it

ample-auctex

**Comment by justbur** [comment]
Thank you!

**Comment by jordonbiondo** [comment]
Looks good, does that screenshot have the powerline changes you made?

I also added the auctex stuff to the other themes which worked nicely out of the box.

**Comment by justbur** [comment]
Yes, it does

**Pull request merged**
