### PR TITLE
Update custom-theme-set-faces usage

### PR DESCRIPTION
**Pull request by JeanMax**
This is to fix:
> Warning: setting attribute ‘:X’ of face ‘Y’: nil value is invalid, use ‘unspecified’ instead.

Introduced in emacs 29 with:
https://github.com/emacs-mirror/emacs/commit/824a139434855919073d6ea3c93d57ebd24fc75c

Related to #34

### CODE REVIEW

**Comment by JeanMax** [comment]
Well, I doxed myself on that commit... whatever :D

I've basically run `M-x query-replace-regexp \(:[a-z-]+\) nil → \1 unspecified` on everything.

I've been using your theme since... 10 years ago? Still looking great! Thanks for this haha

**Comment by jordonbiondo** [comment]
Hey! Thank you for the update, I'm happy to hear you've been enjoying the theme!

It might be a few days before I test this out. Do you know if the change to unspecified is backwards compatible? My only concern is the need to introduce a switch to support latest and old versions.

**Comment by JeanMax** [comment]
Ha that's a good point, I didn't test. From what I remember reading, the behavior didn't change, they just added a warning (but take that with a grain of salt).

I'll try to find some time to compile an older emacs and I'll let you know!

**Comment by jordonbiondo** [comment]
All looks good! Thanks again!

**Pull request merged**
